//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jarvis.Resource.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Already Approved.
        /// </summary>
        public static string AlreadyApprovedIssue {
            get {
                return ResourceManager.GetString("AlreadyApprovedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have checked out this asset..
        /// </summary>
        public static string AlreadyCheckOut {
            get {
                return ResourceManager.GetString("AlreadyCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already inspection generated for selected date range.
        /// </summary>
        public static string AlreadyInspectionExists {
            get {
                return ResourceManager.GetString("AlreadyInspectionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is used.
        /// </summary>
        public static string AlreadyUsedToken {
            get {
                return ResourceManager.GetString("AlreadyUsedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset is still in maintenance.
        /// </summary>
        public static string AssetInMaintenanace {
            get {
                return ResourceManager.GetString("AssetInMaintenanace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Identification} Must be Unique.
        /// </summary>
        public static string AssetMustbeUnique {
            get {
                return ResourceManager.GetString("AssetMustbeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset is not exist.
        /// </summary>
        public static string AssetNotActive {
            get {
                return ResourceManager.GetString("AssetNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter correct Asset ID.
        /// </summary>
        public static string AssetNotFound {
            get {
                return ResourceManager.GetString("AssetNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can not delete Parent Task .
        /// </summary>
        public static string can_not_delete_parent_task {
            get {
                return ResourceManager.GetString("can_not_delete_parent_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Delete WO line as it is mapped to Fed by..
        /// </summary>
        public static string CannotDeleteFedByWOLine {
            get {
                return ResourceManager.GetString("CannotDeleteFedByWOLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company code is not valid.
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not active.
        /// </summary>
        public static string DeActiveUser {
            get {
                return ResourceManager.GetString("DeActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete Assigned Issue.
        /// </summary>
        public static string DeleteAssignedIssue {
            get {
                return ResourceManager.GetString("DeleteAssignedIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not Delete Issue other than Open Status.
        /// </summary>
        public static string DeleteOpenAssetIssue {
            get {
                return ResourceManager.GetString("DeleteOpenAssetIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is authrized.
        /// </summary>
        public static string DeviceAuthorized {
            get {
                return ResourceManager.GetString("DeviceAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is not register in owr system.
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not assign to user register company .
        /// </summary>
        public static string DeviceNotRegisterToUserCompany {
            get {
                return ResourceManager.GetString("DeviceNotRegisterToUserCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not authorized, please contact support!.
        /// </summary>
        public static string DeviceUnaAuthorized {
            get {
                return ResourceManager.GetString("DeviceUnaAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your administrator, this device is not authorized..
        /// </summary>
        public static string DeviceUnAuthorizedSupport {
            get {
                return ResourceManager.GetString("DeviceUnAuthorizedSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not registered email address, please try again.
        /// </summary>
        public static string EmailNotRegister {
            get {
                return ResourceManager.GetString("EmailNotRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Something went wrong, please try again.
        ///Contact Support if the problem persists!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error In Create Issue.
        /// </summary>
        public static string Errorincreateissue {
            get {
                return ResourceManager.GetString("Errorincreateissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in update inspection status.
        /// </summary>
        public static string Errorinupdateinspectionstatus {
            get {
                return ResourceManager.GetString("Errorinupdateinspectionstatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {form_name} dont have any task..
        /// </summary>
        public static string FormDontHaveTask {
            get {
                return ResourceManager.GetString("FormDontHaveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form is Used in Workorder.
        /// </summary>
        public static string FormisUsed {
            get {
                return ResourceManager.GetString("FormisUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {form_name} is not exist in system.
        /// </summary>
        public static string FormnotExist {
            get {
                return ResourceManager.GetString("FormnotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {identification} Identification for Category {taskid} must be unique.
        /// </summary>
        public static string IdentificationMustbeunique {
            get {
                return ResourceManager.GetString("IdentificationMustbeunique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection is not exist.
        /// </summary>
        public static string InspectionNotFound {
            get {
                return ResourceManager.GetString("InspectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {assetid} Asset ID for Category {taskid} must be unique.
        /// </summary>
        public static string InternalAssetIDmustbeUnique {
            get {
                return ResourceManager.GetString("InternalAssetIDmustbeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is invalid..
        /// </summary>
        public static string InvalidStatus {
            get {
                return ResourceManager.GetString("InvalidStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is invalid.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Procedure must be unique..
        /// </summary>
        public static string InvalidWorkProcedure {
            get {
                return ResourceManager.GetString("InvalidWorkProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue with WO Line : .
        /// </summary>
        public static string IssueWithTask {
            get {
                return ResourceManager.GetString("IssueWithTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark completed successfully..
        /// </summary>
        public static string MarkedCompleted {
            get {
                return ResourceManager.GetString("MarkedCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be different from the old password!.
        /// </summary>
        public static string NewPasswordMustBeDifferent {
            get {
                return ResourceManager.GetString("NewPasswordMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string nodatafound {
            get {
                return ResourceManager.GetString("nodatafound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This asset have no inspectionform.
        /// </summary>
        public static string Noinspectionform {
            get {
                return ResourceManager.GetString("Noinspectionform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected role is not assign to user.
        /// </summary>
        public static string NotAssignRole {
            get {
                return ResourceManager.GetString("NotAssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected site is not assign to user.
        /// </summary>
        public static string NotAssignSite {
            get {
                return ResourceManager.GetString("NotAssignSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code is not valid.
        /// </summary>
        public static string NotValidGuid {
            get {
                return ResourceManager.GetString("NotValidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Model is not valid.
        /// </summary>
        public static string NotValidModel {
            get {
                return ResourceManager.GetString("NotValidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection pending.
        /// </summary>
        public static string PendingInspection {
            get {
                return ResourceManager.GetString("PendingInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please first verify previous pending inspections.
        /// </summary>
        public static string PendingInspectionAlreadyExists {
            get {
                return ResourceManager.GetString("PendingInspectionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inpsection photo is compalsory to generate inspection.
        /// </summary>
        public static string PhotoCompalsory {
            get {
                return ResourceManager.GetString("PhotoCompalsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully..
        /// </summary>
        public static string PMCategoryDeleted {
            get {
                return ResourceManager.GetString("PMCategoryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete Linked PM Plan.
        /// </summary>
        public static string PMPlanIsLinked {
            get {
                return ResourceManager.GetString("PMPlanIsLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Plans are already existing in this category..
        /// </summary>
        public static string PMPlansExisting {
            get {
                return ResourceManager.GetString("PMPlansExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized User.
        /// </summary>
        public static string QuickSightUnauthorizedUser {
            get {
                return ResourceManager.GetString("QuickSightUnauthorizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Added Successfully.
        /// </summary>
        public static string RecordAdded {
            get {
                return ResourceManager.GetString("RecordAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled successfully..
        /// </summary>
        public static string RecordCancelled {
            get {
                return ResourceManager.GetString("RecordCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully!.
        /// </summary>
        public static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Already Exists.
        /// </summary>
        public static string RecordExist {
            get {
                return ResourceManager.GetString("RecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully.
        /// </summary>
        public static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you an email with reset password instructions..
        /// </summary>
        public static string ResetPasswordLinkSent {
            get {
                return ResourceManager.GetString("ResetPasswordLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an access of this role..
        /// </summary>
        public static string RoleAccessRevoke {
            get {
                return ResourceManager.GetString("RoleAccessRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date range selection.
        /// </summary>
        public static string SelectValidDate {
            get {
                return ResourceManager.GetString("SelectValidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an access to this site.
        /// </summary>
        public static string SiteAccessRevoked {
            get {
                return ResourceManager.GetString("SiteAccessRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete this task as it is already linked..
        /// </summary>
        public static string TaskAlreadyLinked {
            get {
                return ResourceManager.GetString("TaskAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is expired..
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file formate is incorrect..
        /// </summary>
        public static string UPLOADFILE_INVALIDFORMAT {
            get {
                return ResourceManager.GetString("UPLOADFILE_INVALIDFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Failed.
        /// </summary>
        public static string UPLOADFILE_TITLE {
            get {
                return ResourceManager.GetString("UPLOADFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This username already exist.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        public static string UsernamePasswordincorrect {
            get {
                return ResourceManager.GetString("UsernamePasswordincorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exists.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid date.
        /// </summary>
        public static string ValidDatetime {
            get {
                return ResourceManager.GetString("ValidDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is valid..
        /// </summary>
        public static string ValidToken {
            get {
                return ResourceManager.GetString("ValidToken", resourceCulture);
            }
        }
    }
}
