version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 165183897698.dkr.ecr.us-east-2.amazonaws.com/conduit-qa-be-ecr
      - echo Installing EB CLI...
      
  build:
    commands:
      - echo Building Docker image...
      - cd ./Jarvis
      - docker build -f dockerfile -t conduit-qa-be-ecr .

  post_build:
    commands:
      - echo Tagging Docker image...
      - docker tag conduit-qa-be-ecr:latest 165183897698.dkr.ecr.us-east-2.amazonaws.com/conduit-qa-be-ecr:latest
      - echo Pushing Docker image to ECR...
      - docker push 165183897698.dkr.ecr.us-east-2.amazonaws.com/conduit-qa-be-ecr:latest