using System;
using System.Collections.Generic;
using System.Text;

namespace Jarvis.ViewModels.RequestResponseViewModel
{
    public class GetAllCalanderWorkordersResponseModel
    {
        public Guid wo_id { get; set; }
        public string wo_number { get; set; } // this will be autogenerated.
        public string manual_wo_number { get; set; } // this user will enter .
        public string po_number { get; set; }
        public string title { get; set; }
        public int wo_type { get; set; }
        public string description { get; set; }
        public int status { get; set; }
        public DateTime? due_date { get; set; }
        public DateTime? start_date { get; set; }
        public Nullable<DateTime> completed_date { get; set; }
        public string due_in { get; set; }
        public bool is_overdue { get; set; }
        public Guid? responsible_party_id { get; set; }
        public string responsible_party_name { get; set; }
        public status_wise_asset_count_obj status_wise_asset_count_obj { get; set; }
        public List<workorder_assigned_users_list> wo_assigned_technicians_list { get; set; }
        public List<workorder_assigned_users_list> wo_assigned_leads_list { get; set; }
        public List<wo_vendors_list_class> wo_vendors_list { get; set; }
    }
    public class workorder_assigned_users_list
    {
        public Guid user_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        // public string profile_picture_name { get; set; }
    }
    public class wo_vendors_list_class
    {
        public Guid? vendor_id { get; set; }
        public string vendor_name { get; set; }
        public string vendor_email { get; set; }
    }
}
