//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis.Service.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jarvis.Service.Resources.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Due.
        /// </summary>
        public static string ActivityPMDueHeader {
            get {
                return ResourceManager.GetString("ActivityPMDueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {pm_name} for {Asset_Name} is overdue..
        /// </summary>
        public static string ActivityPMDueMeterHoursMessage {
            get {
                return ResourceManager.GetString("ActivityPMDueMeterHoursMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested {Asset_Name} has been auto approved.
        /// </summary>
        public static string AutoApprovedInspectionOperator {
            get {
                return ResourceManager.GetString("AutoApprovedInspectionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Auto Approved.
        /// </summary>
        public static string AutoApprovedInspectionOperatorHeader {
            get {
                return ResourceManager.GetString("AutoApprovedInspectionOperatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator {Operator_Name} has been auto approved for {Asset_Name}.
        /// </summary>
        public static string AutoApproveInspection {
            get {
                return ResourceManager.GetString("AutoApproveInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Auto Approved.
        /// </summary>
        public static string AutoApproveInspectionHeader {
            get {
                return ResourceManager.GetString("AutoApproveInspectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {Manager_Name} has inspected and created issue of {Asset_Name} for {Attribute_Name}.
        /// </summary>
        public static string CreateIssue {
            get {
                return ResourceManager.GetString("CreateIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Created.
        /// </summary>
        public static string CreateIssueHeader {
            get {
                return ResourceManager.GetString("CreateIssueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {Manager_Name} has approved the asset and created issue for {Asset_Name}.
        /// </summary>
        public static string CreateIssueWithApprovedAsset {
            get {
                return ResourceManager.GetString("CreateIssueWithApprovedAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Approved &amp; Issue Created.
        /// </summary>
        public static string CreateIssueWithApprovedAssetHeader {
            get {
                return ResourceManager.GetString("CreateIssueWithApprovedAssetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Completed.
        /// </summary>
        public static string InspectionCompletedHeader {
            get {
                return ResourceManager.GetString("InspectionCompletedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Completed on {Asset_Name}..
        /// </summary>
        public static string InspectionCompletedMessage {
            get {
                return ResourceManager.GetString("InspectionCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Accept request.
        /// </summary>
        public static string InspectionCreatedHeader {
            get {
                return ResourceManager.GetString("InspectionCreatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Asset_Name} is requested by {operator_name}..
        /// </summary>
        public static string InspectionCreatedMessage {
            get {
                return ResourceManager.GetString("InspectionCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Created.
        /// </summary>
        public static string IssueCreatedHeader {
            get {
                return ResourceManager.GetString("IssueCreatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {issue_name} Created..
        /// </summary>
        public static string IssueCreatedMessage {
            get {
                return ResourceManager.GetString("IssueCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Resolved.
        /// </summary>
        public static string IssueResolvedHeader {
            get {
                return ResourceManager.GetString("IssueResolvedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {issue_name} Resolved..
        /// </summary>
        public static string IssueResolvedMessage {
            get {
                return ResourceManager.GetString("IssueResolvedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {Manager_Name} has inspected and approved {Asset_Name}.
        /// </summary>
        public static string ManagerApproveInspection {
            get {
                return ResourceManager.GetString("ManagerApproveInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Approved.
        /// </summary>
        public static string ManagerApproveInspectionHeader {
            get {
                return ResourceManager.GetString("ManagerApproveInspectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {Manager_Name} has inspected and created issue for {Asset_Name}.
        /// </summary>
        public static string NewIssueForInspection {
            get {
                return ResourceManager.GetString("NewIssueForInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Created.
        /// </summary>
        public static string NewIssueForInspectionHeader {
            get {
                return ResourceManager.GetString("NewIssueForInspectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator {Operator_Name} is asking for approval for {Asset_Name}.
        /// </summary>
        public static string PendingNewInspection {
            get {
                return ResourceManager.GetString("PendingNewInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Approval.
        /// </summary>
        public static string PendingNewInspectionHeader {
            get {
                return ResourceManager.GetString("PendingNewInspectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {pm_name} for {Asset_Name} will be due in {time}..
        /// </summary>
        public static string PMNotificationDueDateReminder {
            get {
                return ResourceManager.GetString("PMNotificationDueDateReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Due Reminder.
        /// </summary>
        public static string PMNotificationDueDateReminderHeader {
            get {
                return ResourceManager.GetString("PMNotificationDueDateReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Due - Final Notification for {Asset_Name}.
        /// </summary>
        public static string PMNotificationFinalReminderHeader {
            get {
                return ResourceManager.GetString("PMNotificationFinalReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Upcoming - 1st Notification for {Asset_Name}.
        /// </summary>
        public static string PMNotificationFirstReminderHeader {
            get {
                return ResourceManager.GetString("PMNotificationFirstReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {pm_name} for {Asset_Name} ..
        /// </summary>
        public static string PMNotificationMeterHoursReminder {
            get {
                return ResourceManager.GetString("PMNotificationMeterHoursReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Due Reminder.
        /// </summary>
        public static string PMNotificationMeterHoursReminderHeader {
            get {
                return ResourceManager.GetString("PMNotificationMeterHoursReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {pm_name} for {Asset_Name} is due now..
        /// </summary>
        public static string PMNotificationOnDue {
            get {
                return ResourceManager.GetString("PMNotificationOnDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Due.
        /// </summary>
        public static string PMNotificationOnDueHeader {
            get {
                return ResourceManager.GetString("PMNotificationOnDueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM Upcoming - 2nd Notification for {Asset_Name}.
        /// </summary>
        public static string PMNotificationSecondReminderHeader {
            get {
                return ResourceManager.GetString("PMNotificationSecondReminderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {Manager_Name} has inspected and Rejected {Asset_Name}.
        /// </summary>
        public static string RejectInspection {
            get {
                return ResourceManager.GetString("RejectInspection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Rejected.
        /// </summary>
        public static string RejectInspectionHeader {
            get {
                return ResourceManager.GetString("RejectInspectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager {Manager_Name} has updated the priority of issue to {Priority} for {Asset_Name}.
        /// </summary>
        public static string UpdateIssuePriority {
            get {
                return ResourceManager.GetString("UpdateIssuePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Issue Priority.
        /// </summary>
        public static string UpdateIssuePriorityHeader {
            get {
                return ResourceManager.GetString("UpdateIssuePriorityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Maintenancestaff_Name} has updated the status of issue to {WorkOrder_Status} of {Attribute_Name} for {Asset_Name}.
        /// </summary>
        public static string UpdateIssueStatus {
            get {
                return ResourceManager.GetString("UpdateIssueStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Issue Status.
        /// </summary>
        public static string UpdateIssueStatusHeader {
            get {
                return ResourceManager.GetString("UpdateIssueStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Created.
        /// </summary>
        public static string WorkOrderCreatedHeader {
            get {
                return ResourceManager.GetString("WorkOrderCreatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {title} Created {workorder_type} for Asset {Asset_Name}..
        /// </summary>
        public static string WorkOrderCreatedMessage {
            get {
                return ResourceManager.GetString("WorkOrderCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {title} Updated, Date changes to {date_value} for Asset {Asset_Name}.
        /// </summary>
        public static string WorkOrderDateUpdatedMessage {
            get {
                return ResourceManager.GetString("WorkOrderDateUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Deleted.
        /// </summary>
        public static string WorkOrderDeletedHeader {
            get {
                return ResourceManager.GetString("WorkOrderDeletedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {title} Deleted on Status {status_value} for Asset {Asset_Name}..
        /// </summary>
        public static string WorkOrderDeletedMessage {
            get {
                return ResourceManager.GetString("WorkOrderDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Issue Linked.
        /// </summary>
        public static string WorkOrderIssueLinkHeader {
            get {
                return ResourceManager.GetString("WorkOrderIssueLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{issue_number} {title} Issue Linked.
        /// </summary>
        public static string WorkOrderIssueLinkMessage {
            get {
                return ResourceManager.GetString("WorkOrderIssueLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Issue Unlinked.
        /// </summary>
        public static string WorkOrderIssueUnLinkHeader {
            get {
                return ResourceManager.GetString("WorkOrderIssueUnLinkHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{issue_number} {title} Issue Unlinked.
        /// </summary>
        public static string WorkOrderIssueUnLinkMessage {
            get {
                return ResourceManager.GetString("WorkOrderIssueUnLinkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order Updated.
        /// </summary>
        public static string WorkOrderUpdatedHeader {
            get {
                return ResourceManager.GetString("WorkOrderUpdatedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {title} Updated, Status changes to {status_value} for Asset {Asset_Name}..
        /// </summary>
        public static string WorkOrderUpdatedMessage {
            get {
                return ResourceManager.GetString("WorkOrderUpdatedMessage", resourceCulture);
            }
        }
    }
}
